// Mock data copied from server seed for offline mode
export let categories = [];

const images = [
  "/images/WhatsApp Image 2026-01-10 at 11.34.58.jpeg",
  "/images/WhatsApp Image 2026-01-11 at 08.30.04.jpeg",
  "/images/WhatsApp Image 2026-01-11 at 08.30.05.jpeg",
  "/images/WhatsApp Image 2026-01-11 at 08.30.06.jpeg",
  "/images/WhatsApp Image 2026-01-11 at 08.30.06 (1).jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.35.jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.35 (1).jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.36.jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.37.jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.37 (1).jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.37 (2).jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.38.jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.39.jpeg",
  "/images/WhatsApp Image 2026-01-12 at 07.36.39 (1).jpeg",
];

export let products = [
  {
    id: 1,
    name: "Handmade Crochet Item #1",
    slug: "handmade-item-1",
    description: "Beautiful handcrafted piece made with love and premium materials. Perfect for gifts or personal collection.",
    price: "45.00",
    image: images[0],
    categoryId: 1,
    isNew: true,
    madeToOrder: true,
    materials: "Premium Yarn, Polyester Fiberfill",
    careInstructions: "Spot clean only.",
    dimensions: "Standard size",
  },
  {
    id: 2,
    name: "Handmade Crochet Item #2",
    slug: "handmade-item-2",
    description: "Expertly crafted with attention to detail. Each piece is unique and made with care.",
    price: "38.00",
    image: images[1],
    categoryId: 1,
    madeToOrder: true,
    materials: "Quality Yarn, Fiberfill",
    dimensions: "Standard size",
  },
  {
    id: 3,
    name: "Handmade Crochet Item #3",
    slug: "handmade-item-3",
    description: "Luxuriously soft and comfortable. Perfect for everyday use or special occasions.",
    price: "120.00",
    originalPrice: "150.00",
    image: images[2],
    categoryId: 1,
    materials: "Premium Materials",
    careInstructions: "Gentle care recommended",
    dimensions: "Standard size",
  },
  {
    id: 4,
    name: "Handmade Crochet Item #4",
    slug: "handmade-item-4",
    description: "A delightful creation perfect for decoration or everyday use. Handmade with passion.",
    price: "85.00",
    image: images[3],
    categoryId: 1,
    isNew: true,
    materials: "Soft Materials",
    dimensions: "Standard size",
  },
  {
    id: 5,
    name: "Handmade Crochet Item #5",
    slug: "handmade-item-5",
    description: "Stylish and durable handmade creation. A versatile addition to any collection.",
    price: "55.00",
    image: images[4],
    categoryId: 1,
    materials: "Quality Yarn",
    dimensions: "Standard size",
  },
  {
    id: 6,
    name: "Handmade Crochet Item #6",
    slug: "handmade-item-6",
    description: "Warm and fashionable. Perfect for gifting or keeping for yourself.",
    price: "35.00",
    image: images[5],
    categoryId: 1,
    materials: "Premium Yarn",
    dimensions: "Standard size",
  },
  {
    id: 7,
    name: "Handmade Crochet Item #7",
    slug: "handmade-item-7",
    description: "Beautifully handcrafted. Adds a personal touch to any space.",
    price: "32.00",
    image: images[6],
    categoryId: 1,
    isNew: true,
    materials: "Quality Materials",
    dimensions: "Standard size",
  },
  {
    id: 8,
    name: "Handmade Crochet Item #8",
    slug: "handmade-item-8",
    description: "Textured and comfortable. A wonderful addition to your collection.",
    price: "42.00",
    image: images[7],
    categoryId: 1,
    materials: "Quality Materials",
    dimensions: "Standard size",
  },
  {
    id: 9,
    name: "Handmade Crochet Item #9",
    slug: "handmade-item-9",
    description: "Classic design with modern appeal. Perfect for any occasion.",
    price: "28.00",
    image: images[8],
    categoryId: 1,
    materials: "Premium Yarn",
    dimensions: "Standard size",
  },
  {
    id: 10,
    name: "Handmade Crochet Item #10",
    slug: "handmade-item-10",
    description: "Stylish and functional. A versatile piece for any collection.",
    price: "24.00",
    image: images[9],
    categoryId: 1,
    madeToOrder: true,
    materials: "Quality Yarn",
    dimensions: "Standard size",
  },
  {
    id: 11,
    name: "Handmade Crochet Item #11",
    slug: "handmade-item-11",
    description: "Adorable and charming. Perfect gift or personal keepsake.",
    price: "52.00",
    image: images[10],
    categoryId: 1,
    madeToOrder: true,
    materials: "Premium Materials",
    dimensions: "Standard size",
  },
  {
    id: 12,
    name: "Handmade Crochet Item #12",
    slug: "handmade-item-12",
    description: "Beautiful craftsmanship in every detail. A true work of art.",
    price: "68.00",
    image: images[11],
    categoryId: 1,
    materials: "Quality Materials",
    dimensions: "Standard size",
  },
  {
    id: 13,
    name: "Handmade Crochet Item #13",
    slug: "handmade-item-13",
    description: "Elegant design with timeless appeal. Perfect for special occasions.",
    price: "58.00",
    image: images[12],
    categoryId: 1,
    isNew: true,
    materials: "Premium Yarn",
    dimension: "Standard size",
  },
  {
    id: 14,
    name: "Handmade Crochet Item #14",
    slug: "handmade-item-14",
    description: "Unique and one-of-a-kind. Each piece is specially crafted.",
    price: "47.00",
    image: images[13],
    categoryId: 1,
    madeToOrder: true,
    materials: "Quality Yarn",
    dimensions: "Standard size",
  },
];

export let blogPosts = [
  {
    id: 1,
    title: "Getting Started with Amigurumi: A Beginner's Guide",
    slug: "getting-started-with-amigurumi",
    excerpt: "Learn the basics of creating adorable crocheted stuffed animals with this comprehensive beginner's guide to amigurumi.",
    content: "Amigurumi is the Japanese art of crocheting small stuffed animals and creatures. In this guide, we'll cover everything you need to know to get started...",
    image: "/images/blog/amigurumi-guide.jpg",
    category: "Tutorials",
    author: "Geraldin",
    readTime: "8 min read",
  },
  {
    id: 2,
    title: "5 Must-Have Yarns for Your Next Project",
    slug: "must-have-yarns-next-project",
    excerpt: "Discover our top yarn recommendations for different types of crochet projects, from cozy blankets to delicate accessories.",
    content: "Choosing the right yarn can make or break your crochet project. Here are our top 5 recommendations for different project types...",
    image: "/images/blog/yarn-selection.jpg",
    category: "Materials",
    author: "Geraldin",
    readTime: "5 min read",
  },
  {
    id: 3,
    title: "How to Care for Your Handmade Crochet Items",
    slug: "caring-for-handmade-crochet",
    excerpt: "Tips and tricks for keeping your handcrafted crochet pieces looking beautiful for years to come.",
    content: "Your handmade crochet items deserve special care to maintain their beauty and longevity. Here's how to properly care for them...",
    image: "/images/blog/crochet-care.jpg",
    category: "Tips",
    author: "Geraldin",
    readTime: "4 min read",
  },
  {
    id: 4,
    title: "Creating a Cozy Home with Crochet Decor",
    slug: "cozy-home-crochet-decor",
    excerpt: "Transform your living space with handmade crochet pieces that add warmth and personality to any room.",
    content: "Adding handmade crochet elements to your home decor creates a warm, inviting atmosphere that can't be replicated with store-bought items...",
    image: "/images/blog/home-decor.jpg",
    category: "Inspiration",
    author: "Geraldin",
    readTime: "6 min read",
  },
  {
    id: 5,
    title: "The Art of Color Combinations in Crochet",
    slug: "color-combinations-crochet",
    excerpt: "Master the art of choosing beautiful color palettes for your crochet projects with these expert tips.",
    content: "Color selection is one of the most exciting parts of starting a new crochet project. Learn how to create stunning color combinations...",
    image: "/images/blog/color-theory.jpg",
    category: "Tutorials",
    author: "Geraldin",
    readTime: "7 min read",
  },
];

export let artistProfile = {
  id: 1,
  name: "Geraldin",
  bio: "Hey! I'm Geraldin — 20, obsessed with color, and I make playful crochet pieces from my tiny studio.",
  story: "I started making stuff as a kid with my grandma's yarn and never stopped. NAIA is my place to drop bold, wearable pieces that mix street energy with cozy vibes.",
  image: "/images/WhatsApp Image 2026-01-12 at 07.36.35 (1).jpeg",
  instagramUrl: "https://instagram.com/naia",
  pinterestUrl: "https://pinterest.com/naia",
  etsyUrl: "https://etsy.com/shop/naia",
};
